-- 通常のデプロイは drizzle-kit push なので、このファイルは記録用。
--
-- チャンネル限定投稿（channel_only）の撤去。
--
-- 2026-07-23 の「こっそりモードをチャンネルに統合適用」で、コンポーザの同じトグルが
-- channelOnly ではなく kossori を立てるようになり、以降この列を true にできる経路は
-- クライアントに存在しなくなった。本番の該当行も 0 件（確認済み）。
--
-- 残しておくと「CH限定という機能がある」と読めてしまい、実際に設計判断を誤らせた。
-- channel_uri（所属チャンネル）は CH TL の実装そのものなので残す。消すのは
-- 「グローバルTLに出さない」フラグだけ。
--
-- 順序: AppView / bot / クライアントのデプロイが先。この DROP は最後に流すこと。
-- 先に列を落とすと、まだ channel_only を select している旧コードが落ちる。
ALTER TABLE "nagi"."posts" DROP COLUMN IF EXISTS "channel_only";
